### PR TITLE
Add support for reindex asset endpoint

### PR DESCRIPTION
**Pull request by defect**
This adds support for the admin API route to synchronously reindex a single asset: https://github.com/tumblr/collins/blob/master/conf/routes#L50

Since collins is async with how it updates Solr on asset updates, if you read an asset right after modifying it you might get stale data back. The idea here is that we can hit this endpoint for the cases where the read-after-write consistency is important to make sure we're consistent, at the cost of an extra API call and Solr op.

@tumblr/collins

### CODE REVIEW

**Comment by alex-laties** [comment]
Definitely document that this should be used sparingly, as triggering a bunch of index rebuilds puts a lot of stress on solr and is a big reason why collins does lazy index rebuilds

**Review by Mitsuwa — APPROVED** [review]

**Comment by defect** [comment]
@alex-laties Yup, i'll add a comment on the method and the `repopulate_solr!` method above. FWIW though I don't think it'll be that heavy. It only triggers a `softCommit` (no flush to disk or opening new segments) and it's what we do for all asset updates, though normally batched over some time period.

**Review by byxorna — APPROVED** [review]
fuck yea!

**Comment by esquireofoz** [comment]
Yes, please!

**Review by roymarantz — APPROVED** [review]
are there statistics available for how often this is used?
extra credit for stats on how long the reindex takes

**Review by tumblr-dockerhub-user — APPROVED** [review]

**Comment by defect** [comment]
@roymarantz Given that i don't think anyone remembered this endpoint existed i'm pretty sure it's not widely used :) Especially at Tumblr. As for the reindex time i think it depends on the setup, but even with our fairly fat assets with a lot of attributes it takes less than half a second to reindex an asset.

**Pull request merged**
